language: go
go:
  - 1.7
  - 1.8
  - 1.9
install: 
    - wget "https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.tar.gz"
    - mkdir -p $HOME/bin
    - tar -vxz -C $HOME/bin --strip=1 -f glide-0.10.2-linux-amd64.tar.gz
    - export PATH="$HOME/bin:$PATH"
    - glide install
    - go get -v ./
script:
    - go test -v -race ./...
